In [1]:
#1. Import the numpy package under the name np (★☆☆)
#(hint: import … as …)
import numpy as np

In [2]:
#2.Print the numpy version and the configuration (★☆☆)
#(hint: np.__version__, np.show_config)
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

In [3]:
#3. Create a null vector of size 10 (★☆☆)
#(hint: np.zeros)
def null_array(n):
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array (★☆☆)
#(hint: size, itemsize)
x=np.array([100,20,34])
print(x.size*x.itemsize)

12


In [5]:
#5.How to get the documentation of the numpy add function from the command line? (★☆☆)
#(hint: np.info)
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#(hint: array[4])
x = np.zeros(10)
print(x)
print("Update 5th value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update 5th value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7.Create a vector with values ranging from 10 to 49 (★☆☆)
#(hint: np.arange)
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#8. Reverse a vector (first element becomes last) (★☆☆)
#(hint: array[::-1])
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#(hint: reshape)
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) 

arr=np.array([1,2,0,0,4,0])
out=np.nonzero(arr)
print(out)

(array([0, 1, 4], dtype=int64),)


In [11]:
#11.Create a 3x3 identity matrix.
#(hint: np.eye)
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12.Create a 3x3x3 array with random values
#(hint: np.random.random)
x=np.random.random((3,3,3))
print(x)

[[[0.85343896 0.83442513 0.75730178]
  [0.60403969 0.78169216 0.8539517 ]
  [0.26510367 0.48966288 0.20272358]]

 [[0.23605751 0.9834473  0.33787604]
  [0.20644212 0.9113565  0.57925282]
  [0.85192208 0.53912854 0.96093346]]

 [[0.25332136 0.12239868 0.26323784]
  [0.74435098 0.60941622 0.50039225]
  [0.40157212 0.58344091 0.11649299]]]


In [13]:
#13.Create a 10x10 array with random values and find the minimum and maximum values 
#(hint: min, max)
x=np.random.random((10,10))
xmin,xmax=x.min(),x.max()
print(xmin,xmax)

0.002009050160548087 0.9979720098128482


In [14]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
#(hint: mean)
x=np.random.random(30)
v=np.mean(x)
v

0.5484757784177746

In [15]:
#15. Create a 2d array with 1 on the border and 0 inside.
#(hint: array[1:-1, 1:-1])
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
#(hint: np.pad)
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#17. What is the result of the following expression? (★☆☆)
#(hint: NaN = not a number, inf = infinity)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
#(hint: np.diag)
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
#(hint: array[::2])

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
#(hint: np.unravel_index)
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#(hint: np.tile)
arr = np.array([[0,1],[1,0]])
repetitions = (4,4)
arr2 = np.tile(arr, repetitions)
print(arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#22.Normalize a 5x5 random matrix 
#(hint: (x - min) / (max - min))
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.38701601 0.06266692 0.67996549 0.05684772 0.78031297]
 [0.97770807 0.56455116 0.79710673 0.05482892 0.42708773]
 [0.00826541 0.79121492 0.08023901 0.59443556 0.7784673 ]
 [0.96819736 0.         0.5205483  0.38068205 0.58884312]
 [1.         0.24237621 0.43461048 0.04486645 0.89038985]]


In [23]:
#23.Create a custom dtype that describes a color as four unsigned bytes (RGBA)
#(hint: np.dtype)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
#(hint: np.dot | @)
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
#25.Given a 1D array, negate all elements which are between 3 and 8, in place.
#(hint: >, <=)
arr = np.arange(11)
arr[(arr>3) & (arr<=8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#26. What is the output of the following script? (★☆☆)
#(hint: np.sum)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))



9
10


In [27]:
#27. Consider an integer vector Z, which of these expressions are legal?
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z

In [28]:
#28.What are the result of the following expressions
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_12236\2353117617.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\bharath.g\AppData\Local\Temp\ipykernel_12236\2353117617.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [29]:
#29. How to round away from zero a float array ?
#(hint: np.uniform, np.copysign, np.ceil, np.abs)
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[ -3.   4.  -4.   2.  -9.   8.   4.  -3.   9. -10.]


In [30]:
#30.How to find common values between two arrays?
#(hint: np.intersect1d)
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
print(np.intersect1d(ar1, ar2))

[1 3 4]


In [31]:
#31.How to ignore all numpy warnings (not recommended)?
#(hint: np.seterr, np.errstate)

data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [32]:
#32. Is the following expressions true? 
#(hint: imaginary number)
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [33]:
#33. How to get the dates of yesterday, today and tomorrow? 
#(hint: np.datetime64, np.timedelta64)
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2023-06-11
2023-06-10
2023-06-12


In [34]:
#34. How to get all the dates corresponding to the month of July 2016?
#(hint: np.arange(dtype=datetime64['D']))
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [35]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
#(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [36]:
#36. Extract the integer part of a random array using 5 different methods
#(hint: %, np.floor, np.ceil, astype, np.trunc)
Z = np.random.uniform(0,10,10)

print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[1. 5. 3. 7. 0. 1. 9. 9. 2. 0.]
[1. 5. 3. 7. 0. 1. 9. 9. 2. 0.]
[1. 5. 3. 7. 0. 1. 9. 9. 2. 0.]
[1 5 3 7 0 1 9 9 2 0]
[1. 5. 3. 7. 0. 1. 9. 9. 2. 0.]


In [37]:
#37.Create a 5x5 matrix with row values ranging from 0 to 4 
#(hint: np.arange)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [38]:
#38.Consider a generator function that generates 10 integers and use it to build an array 
#(hint: np.fromiter)
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
#(hint: np.linspace)
l = np.linspace(0,1,11,endpoint=False)[1:]
print(l)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
#40.Create a random vector of size 10 and sort it 
#(hint: sort)
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06314484 0.2768189  0.39495869 0.41059351 0.52296644 0.54993385
 0.56476287 0.59382516 0.73134201 0.96619398]


In [41]:
#41. How to sum a small array faster than np.sum?
#(hint: np.add.reduce)
Z = np.arange(10)
np.add.reduce(Z)


45

In [42]:
#42. Consider two random array A and B, check if they are equal
#(hint: np.allclose, np.array_equal)
A = np.random.randint(0,4,3)
B = np.random.randint(0,4,3)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)


False
False


In [43]:
#43. Make an array immutable (read-only)
#(hint: flags.writeable)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [44]:
#44.Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.16250319 1.15714293 0.93020143 0.86944406 0.98661294 1.08824332
 0.91038751 0.4602655  0.90538743 0.60482834]
[0.9260711  0.7769983  0.46916331 0.03008741 0.75952917 0.69563138
 0.15116879 0.94135348 1.42556338 0.56781443]


In [45]:
#45.Create random vector of size 10 and replace the maximum value by 0
#(hint: argmax)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.13468928 0.25367466 0.17081686 0.75748389 0.51520728 0.
 0.01187694 0.63204794 0.14225243 0.17311676]


In [46]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
#(hint: np.meshgrid)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
#47.Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
#(hint: np.subtract.outer)
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [48]:
#48.Print the minimum and maximum representable value for each numpy scalar type 
#(hint: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [49]:
#49. How to print all the values of an array? 
#(hint: np.set_printoptions)
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
#50.How to find the closest value (to a given scalar) in a vector?
#(hint: argmin)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index]) 

43


In [51]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
#(hint: dtype)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

C:\Users\bharath.g\AppData\Local\Temp\ipykernel_12236\3856014852.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [52]:
#52.Consider a random vector with shape (100,2) representing coordinates, find point by point distances 
#(hint: np.atleast_2d, T, np.sqrt)
a= np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.55659602 0.1049504  0.48332948 0.87921704 0.72636696
  0.62933419 0.64818647 0.18846699 0.51846307 0.78068574 0.27046822
  0.7543328  0.1898472  0.34843241 0.56866997 0.50028422 0.06608813
  0.40516364 0.34968972 1.04077884 0.24172183 0.40990707 0.5756378
  0.30792543 0.84641253 0.16831565 0.16309342 0.06987784 0.09400776
  0.75129388 0.98420889 0.95604282 0.76992561 0.16846514 0.65014186
  0.37233696 0.39919624 0.1070311  0.59461123 0.70509669 0.70902837
  0.523731   0.40119893 0.62118119 0.79264926 0.43148199 0.15714658
  0.74157393 0.76883626 0.33961997 0.43044433 0.30892933 0.74596312
  0.53956947 0.3825502  0.58391178 0.38134121 0.40499112 0.65065885
  0.63455646 0.12787306 0.62244327 0.46531917 0.79008318 0.54057028
  0.08864788 0.6475923  0.52605071 0.2422148  0.62488528 0.10991568
  0.16159407 0.28033498 0.07681865 0.79997081 0.72398773 0.45491251
  0.2821753  0.48645782 0.40759428 0.52533359 0.72970963 0.08733865
  0.70449431 0.70034257 0.49941004 0.87079609 0.5

In [53]:
#53.How to convert a float (32 bits) array into an integer (32 bits) in place?
#(hint: astype(copy=False))
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
#54. How to read the following file?
#(hint: np.genfromtxt)
#1, 2, 3, 4, 5
#6,  ,  , 7, 8
#,  , 9,10,11
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_12236\1802376389.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [55]:
#55.What is the equivalent of enumerate for numpy arrays? 
#(hint: np.ndenumerate, np.ndindex)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [56]:
#56.Generate a generic 2D Gaussian-like array 
#(hint: np.meshgrid, np.exp)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
#57.How to randomly place p elements in a 2D array? 
#(hint: np.put, np.random.choice)
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
#58. Subtract the mean of each row of a matrix 
#(hint: mean(axis=,keepdims=))
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[ 0.28360709 -0.22889815 -0.11725724  0.41384261  0.08736914 -0.33417372
  -0.52386527  0.07575659 -0.06824933  0.41186828]
 [-0.09484334  0.51880642 -0.33666177 -0.32208049  0.12649882 -0.08701493
   0.41753621  0.07393325 -0.02501326 -0.2711609 ]
 [-0.21341412  0.04416753  0.58365834  0.0606369  -0.34970136 -0.00371797
  -0.34266703 -0.20014124  0.16422081  0.25695814]
 [-0.07497674  0.29152598  0.22624763  0.00070516 -0.3895283   0.224585
  -0.28441214 -0.09065693  0.0163008   0.08020953]
 [-0.58162899  0.27562802 -0.21761985 -0.01501916  0.1674756   0.21191955
   0.31223891  0.02402153 -0.30193963  0.12492402]]


In [59]:
#59.How to sort an array by the nth column?
#(hint: argsort)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[2 5 3]
 [0 7 9]
 [3 2 2]]
[[3 2 2]
 [2 5 3]
 [0 7 9]]


In [60]:
#60.How to tell if a given 2D array has null columns?
#(hint: any, ~)
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


False


In [61]:
#61.Find the nearest value from a given value in an array (★★☆)
#(hint: np.abs, argmin, flat)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.49178393605445525


In [62]:
#62.Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
#(hint: np.nditer)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
#63.Create an array class that has a name attribute 
#(hint: class method)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [64]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
#(hint: np.bincount | np.add.at)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[6. 2. 1. 3. 4. 3. 4. 2. 2. 3.]
[11.  3.  1.  5.  7.  5.  7.  3.  3.  5.]


In [65]:
#65.How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
#(hint: np.bincount)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [66]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
#(hint: np.unique)
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256 )+ I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [67]:
#67.Considering a four dimensions array, how to get sum over the last two axis at once? 
#(hint: sum(axis=(-2,-1)))
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[64 52 55 61]
 [53 46 38 53]
 [63 39 63 35]]
[[64 52 55 61]
 [53 46 38 53]
 [63 39 63 35]]


In [68]:
#68.Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
#(hint: np.bincount)
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.47052765 0.54002201 0.40574791 0.40030077 0.40577026 0.52002347
 0.5917547  0.68137784 0.50706435 0.49798194]


In [69]:
#69. How to get the diagonal of a dot product? 
#(hint: np.diag)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([0.92178666, 0.57840317, 1.11837427, 0.84257092, 1.99641782])

In [70]:
#70.Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 
#(hint: array[:, :, None])
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [71]:
#71.Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 
#(hint: array[[]] = array[[]])
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [72]:
#72. How to swap two rows of an array?
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [73]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles 
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 2, 59) ( 2, 68) ( 7, 45) ( 7, 92) (11, 11) (11, 65) (21, 30) (21, 94)
 (25, 55) (25, 89) (28, 64) (28, 97) (29, 35) (29, 50) (30, 94) (33, 68)
 (33, 99) (34, 57) (34, 86) (35, 50) (45, 92) (55, 68) (55, 74) (55, 89)
 (57, 86) (59, 68) (64, 97) (68, 74) (68, 99)]


In [74]:
#74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C?
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


In [75]:
# 75. How to compute averages using a sliding window over an array? 
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [76]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [77]:
#77. How to negate a boolean, or to change the sign of a float inplace? 
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1])

In [78]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[15.97017889 13.92867194  3.80905328 19.516412    1.19752657 13.66069549
 11.96916404 13.98055199 17.34856252  9.41771558]


In [79]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[3.98575481e-01 3.80196623e-01 5.20015186e+00 6.82266280e-01
  2.08836364e-01 1.91008924e+00 1.04051520e+01 4.04956349e+00
  8.20164114e+00 2.10800864e+00]
 [7.51935818e+00 1.14860055e+00 9.17288810e+00 4.50340505e+00
  7.70870119e+00 5.59106205e+00 9.02944174e+00 3.21036631e+00
  9.65655163e-01 5.21148082e+00]
 [5.82078591e+00 1.78008430e+00 1.11818567e+01 1.66946122e+00
  7.37155358e+00 5.25060137e+00 6.38441921e+00 6.10978017e+00
  8.50573501e-01 5.21174723e+00]
 [2.71531811e+00 3.53984260e+00 2.54595320e+00 4.49172512e+00
  7.10867419e-01 1.40362673e+00 1.39264056e+01 1.73376961e-01
  8.30511088e+00 2.05763503e+00]
 [1.25848836e-01 1.00196194e+00 5.49471114e+00 1.90791037e-02
  5.51905395e-02 2.17480787e+00 9.91603966e+00 4.64739537e+00
  8.36892810e+00 2.30029042e+00]
 [3.69347817e+00 4.58806320e+00 1.27063003e+01 1.23503012e+00
  6.46237644e+00 4.33828316e+00 4.06893194e+00 8.83574744e+00
  1.32393504e+00 4.62641698e+00]
 [5.15623354e+00 6.66255833e+00 1.62766603e+01 2.24098560e

In [80]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[5 7 8 1 2 7 8 4 7 0]
 [7 0 7 1 0 5 4 2 6 7]
 [9 0 8 9 0 8 2 7 1 4]
 [7 0 2 9 8 5 3 9 2 2]
 [0 4 4 7 1 0 4 8 6 5]
 [8 7 0 4 1 2 2 4 8 5]
 [9 2 1 5 9 9 3 4 2 8]
 [8 9 7 8 7 0 0 9 7 0]
 [5 1 8 2 6 6 9 8 0 1]
 [2 2 0 6 9 4 0 2 9 7]]
[[0 0 0 0 0]
 [0 5 7 8 1]
 [0 7 0 7 1]
 [0 9 0 8 9]
 [0 7 0 2 9]]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_12236\1020413482.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [81]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [82]:
#82. Compute a matrix rank (★★★)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)



10


In [83]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


3


In [84]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 0 2]
   [4 0 2]
   [2 3 0]]

  [[0 2 2]
   [0 2 2]
   [3 0 4]]

  [[2 2 1]
   [2 2 0]
   [0 4 2]]

  [[2 1 2]
   [2 0 0]
   [4 2 1]]

  [[1 2 2]
   [0 0 2]
   [2 1 1]]

  [[2 2 4]
   [0 2 4]
   [1 1 4]]

  [[2 4 0]
   [2 4 0]
   [1 4 0]]

  [[4 0 1]
   [4 0 3]
   [4 0 0]]]


 [[[4 0 2]
   [2 3 0]
   [4 4 0]]

  [[0 2 2]
   [3 0 4]
   [4 0 3]]

  [[2 2 0]
   [0 4 2]
   [0 3 3]]

  [[2 0 0]
   [4 2 1]
   [3 3 4]]

  [[0 0 2]
   [2 1 1]
   [3 4 0]]

  [[0 2 4]
   [1 1 4]
   [4 0 2]]

  [[2 4 0]
   [1 4 0]
   [0 2 0]]

  [[4 0 3]
   [4 0 0]
   [2 0 1]]]


 [[[2 3 0]
   [4 4 0]
   [0 3 2]]

  [[3 0 4]
   [4 0 3]
   [3 2 3]]

  [[0 4 2]
   [0 3 3]
   [2 3 4]]

  [[4 2 1]
   [3 3 4]
   [3 4 3]]

  [[2 1 1]
   [3 4 0]
   [4 3 0]]

  [[1 1 4]
   [4 0 2]
   [3 0 1]]

  [[1 4 0]
   [0 2 0]
   [0 1 1]]

  [[4 0 0]
   [2 0 1]
   [1 1 0]]]


 [[[4 4 0]
   [0 3 2]
   [2 0 4]]

  [[4 0 3]
   [3 2 3]
   [0 4 2]]

  [[0 3 3]
   [2 3 4]
   [4 2 3]]

  [[3 3 4]
   [3 4 3]
   [2 3 1]]

  [[3 4 0]
   

In [85]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 4  3 10 11  6]
 [ 3  7 16  5  8]
 [10 16  5 42  6]
 [11  5 42  2  9]
 [ 6  8  6  9  7]]


In [86]:
#86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [87]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [88]:
#88. How to implement the Game of Life using numpy arrays? (★★★)
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0

In [89]:
#89. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argpartition(-Z,n)[:n]])


[9999 9998 9997 9996 9995]


In [90]:
#91. How to create a record array from a regular array? (★★★)
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [91]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

x = np.random.randint(5e7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.7 µs ± 216 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
221 ns ± 30.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [92]:
#93.Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
#(hint: np.where)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 4 5 6]


In [93]:
#94.Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 2 1]
 [0 0 2]
 [1 3 4]
 [2 3 2]
 [2 2 0]
 [2 4 1]
 [2 3 0]
 [3 4 1]
 [2 3 3]
 [1 2 3]]
[[1 2 1]
 [0 0 2]
 [1 3 4]
 [2 3 2]
 [2 2 0]
 [2 4 1]
 [2 3 0]
 [3 4 1]
 [2 3 3]
 [1 2 3]]
[[1 2 1]
 [0 0 2]
 [1 3 4]
 [2 3 2]
 [2 2 0]
 [2 4 1]
 [2 3 0]
 [3 4 1]
 [2 3 3]
 [1 2 3]]


In [94]:
#95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [95]:
#96. Given a two dimensional array, how to extract unique rows? 
#(hint: np.ascontiguousarray)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 1 0]]


In [96]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 
#(hint: np.einsum)
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.10924404, 0.00788139, 0.23743312, 0.20651134, 0.15864529,
        0.24694304, 0.12563864, 0.19124   , 0.27947096, 0.12946394],
       [0.14011719, 0.01010873, 0.30453341, 0.26487292, 0.20347958,
        0.3167309 , 0.16114502, 0.24528579, 0.35845145, 0.16605137],
       [0.17968134, 0.01296308, 0.3905229 , 0.33966368, 0.26093504,
        0.40616453, 0.20664669, 0.31454584, 0.45966549, 0.21293842],
       [0.29521635, 0.02129834, 0.64162893, 0.55806726, 0.42871614,
        0.66732812, 0.3395204 , 0.51679865, 0.75523017, 0.34985771],
       [0.24449097, 0.01763876, 0.53138141, 0.46217768, 0.35505223,
        0.55266485, 0.2811825 , 0.42800002, 0.62546318, 0.28974361],
       [0.2421642 , 0.0174709 , 0.52632437, 0.45777923, 0.35167328,
        0.54740526, 0.27850655, 0.42392684, 0.61951078, 0.28698619],
       [0.2304825 , 0.01662813, 0.50093514, 0.43569654, 0.334709  ,
        0.52099912, 0.26507175, 0.40347714, 0.58962636, 0.27314233],
       [0.32369925, 0.02335323, 0.7035342

In [97]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
#(hint: np.cumsum, np.interp)
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [98]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
#(hint: np.logical_and.reduce, np.mod)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [99]:
#100.Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
#(hint: np.percentile)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.36047273  0.04044728]
