In [1]:
#1. Import the numpy package under the name np (★☆☆)
#(hint: import … as …)
import numpy as np

In [2]:
#2.Print the numpy version and the configuration (★☆☆)
#(hint: np.__version__, np.show_config)
print(np.__version__)
print(np.show_config())

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/Anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

In [3]:
#3. Create a null vector of size 10 (★☆☆)
#(hint: np.zeros)
def null_array(n):
    x=np.zeros(n)
    return x
print(null_array(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#4. How to find the memory size of any array (★☆☆)
#(hint: size, itemsize)
x=np.array([100,20,34])
print(x.size*x.itemsize)

12


In [5]:
#5.How to get the documentation of the numpy add function from the command line? (★☆☆)
#(hint: np.info)
print(np.info(np.add))


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [6]:
#6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#(hint: array[4])
x = np.zeros(10)
print(x)
print("Update 5th value to 1")
x[4] = 1
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update 5th value to 1
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#7.Create a vector with values ranging from 10 to 49 (★☆☆)
#(hint: np.arange)
v = np.arange(10,49)
print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#8. Reverse a vector (first element becomes last) (★☆☆)
#(hint: array[::-1])
v[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

In [9]:
#9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#(hint: reshape)
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆) 

arr=np.array([1,2,0,0,4,0])
out=np.nonzero(arr)
print(out)

(array([0, 1, 4], dtype=int64),)


In [11]:
#11.Create a 3x3 identity matrix.
#(hint: np.eye)
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#12.Create a 3x3x3 array with random values
#(hint: np.random.random)
x=np.random.random((3,3,3))
print(x)

[[[0.39252379 0.6920608  0.59524421]
  [0.6981453  0.37782616 0.12777181]
  [0.35272918 0.90663777 0.51863642]]

 [[0.32017945 0.71434876 0.94127061]
  [0.71012864 0.58177144 0.01108567]
  [0.705735   0.84956575 0.39377274]]

 [[0.18922997 0.88999553 0.4271984 ]
  [0.00677119 0.55011541 0.42802804]
  [0.66239784 0.71421981 0.48214321]]]


In [13]:
#13.Create a 10x10 array with random values and find the minimum and maximum values 
#(hint: min, max)
x=np.random.random((10,10))
xmin,xmax=x.min(),x.max()
print(xmin,xmax)

0.019617205890975153 0.9899543071647194


In [14]:
#14. Create a random vector of size 30 and find the mean value (★☆☆)
#(hint: mean)
x=np.random.random(30)
v=np.mean(x)
v

0.44776500389433144

In [15]:
#15. Create a 2d array with 1 on the border and 0 inside.
#(hint: array[1:-1, 1:-1])
x = np.ones((5,5))
print(x)
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
#16. How to add a border (filled with 0's) around an existing array? (★☆☆)
#(hint: np.pad)
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [17]:
#17. What is the result of the following expression? (★☆☆)
#(hint: NaN = not a number, inf = infinity)
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [18]:
#18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.
#(hint: np.diag)
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [19]:
#19. Create a 8x8 matrix and fill it with a checkerboard pattern
#(hint: array[::2])

x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
#20.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
#(hint: np.unravel_index)
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [21]:
#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
#(hint: np.tile)
arr = np.array([[0,1],[1,0]])
repetitions = (4,4)
arr2 = np.tile(arr, repetitions)
print(arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [22]:
#22.Normalize a 5x5 random matrix 
#(hint: (x - min) / (max - min))
x= np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print(x)

[[0.95040868 0.         0.05398658 0.04549451 0.94775925]
 [0.69028036 0.30497172 0.56494423 0.83354331 0.35402655]
 [0.1518657  0.87445966 0.69775546 0.19851577 0.98021357]
 [0.79914337 0.3725211  1.         0.76543366 0.93541697]
 [0.23348413 0.29015571 0.86151416 0.8414525  0.20219458]]


In [23]:
#23.Create a custom dtype that describes a color as four unsigned bytes (RGBA)
#(hint: np.dtype)
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [24]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
#(hint: np.dot | @)
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [25]:
#25.Given a 1D array, negate all elements which are between 3 and 8, in place.
#(hint: >, <=)
arr = np.arange(11)
arr[(arr>3) & (arr<=8)] *= -1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [26]:
#26. What is the output of the following script? (★☆☆)
#(hint: np.sum)
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))



9
10


In [27]:
#27. Consider an integer vector Z, which of these expressions are legal?
#Z**Z
#2 << Z >> 2
#Z <- Z
#1j*Z
#Z/1/1
#Z<Z>Z

In [28]:
#28.What are the result of the following expressions
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\2353117617.py:2: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\2353117617.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [29]:
#29. How to round away from zero a float array ?
#(hint: np.uniform, np.copysign, np.ceil, np.abs)
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[  6.  -9. -10.   1.  -1.  -4.  -2.   6.  -4.  -3.]


In [30]:
#30.How to find common values between two arrays?
#(hint: np.intersect1d)
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
print(np.intersect1d(ar1, ar2))

[1 3 4]


In [31]:
#31.How to ignore all numpy warnings (not recommended)?
#(hint: np.seterr, np.errstate)

data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

C:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\nanfunctions.py:1119: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,


array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

In [32]:
#32. Is the following expressions true? 
#(hint: imaginary number)
np.sqrt(-1) == np.emath.sqrt(-1)

False

In [33]:
#33. How to get the dates of yesterday, today and tomorrow? 
#(hint: np.datetime64, np.timedelta64)
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(today)
print(yesterday)
print(tomorrow)

2023-02-21
2023-02-20
2023-02-22


In [34]:
#34. How to get all the dates corresponding to the month of July 2016?
#(hint: np.arange(dtype=datetime64['D']))
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [35]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
#(hint: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [36]:
#36. Extract the integer part of a random array using 5 different methods
#(hint: %, np.floor, np.ceil, astype, np.trunc)
Z = np.random.uniform(0,10,10)

print (Z-Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[0. 3. 9. 1. 8. 7. 2. 6. 4. 6.]
[0. 3. 9. 1. 8. 7. 2. 6. 4. 6.]
[0. 3. 9. 1. 8. 7. 2. 6. 4. 6.]
[0 3 9 1 8 7 2 6 4 6]
[0. 3. 9. 1. 8. 7. 2. 6. 4. 6.]


In [37]:
#37.Create a 5x5 matrix with row values ranging from 0 to 4 
#(hint: np.arange)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)


[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [38]:
#38.Consider a generator function that generates 10 integers and use it to build an array 
#(hint: np.fromiter)
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [39]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
#(hint: np.linspace)
l = np.linspace(0,1,11,endpoint=False)[1:]
print(l)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [40]:
#40.Create a random vector of size 10 and sort it 
#(hint: sort)
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06798929 0.15052671 0.31669416 0.40364327 0.51079989 0.63294692
 0.6510982  0.75120843 0.88600071 0.94231102]


In [41]:
#41. How to sum a small array faster than np.sum?
#(hint: np.add.reduce)
Z = np.arange(10)
np.add.reduce(Z)


45

In [42]:
#42. Consider two random array A and B, check if they are equal
#(hint: np.allclose, np.array_equal)
A = np.random.randint(0,4,3)
B = np.random.randint(0,4,3)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)


False
False


In [43]:
#43. Make an array immutable (read-only)
#(hint: flags.writeable)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [44]:
#44.Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates 
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.88081825 0.54430497 0.77007194 0.6548981  0.33533505 0.81372174
 0.47336776 1.00696259 0.47224106 0.69286969]
[1.49338028 0.44765833 0.00159386 0.92894286 1.28599642 1.13305354
 0.33701871 1.21628492 1.21742734 0.84253671]


In [45]:
#45.Create random vector of size 10 and replace the maximum value by 0
#(hint: argmax)
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.26508434 0.28819956 0.21836969 0.04232947 0.06374963 0.36551129
 0.         0.63222069 0.75283637 0.07498285]


In [46]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area
#(hint: np.meshgrid)
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [47]:
#47.Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
#(hint: np.subtract.outer)
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


In [48]:
#48.Print the minimum and maximum representable value for each numpy scalar type 
#(hint: np.iinfo, np.finfo, eps)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [49]:
#49. How to print all the values of an array? 
#(hint: np.set_printoptions)
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [50]:
#50.How to find the closest value (to a given scalar) in a vector?
#(hint: argmin)
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index]) 

65


In [51]:
#51. Create a structured array representing a position (x,y) and a color (r,g,b)
#(hint: dtype)
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
Z

C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\3856014852.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

In [52]:
#52.Consider a random vector with shape (100,2) representing coordinates, find point by point distances 
#(hint: np.atleast_2d, T, np.sqrt)
a= np.random.random((100,2))
x,y = np.atleast_2d(a[:,0], a[:,1])
d = np.sqrt( (x-x.T)**2 + (y-y.T)**2)
print(d)

[[0.         0.52864027 0.55626235 0.15906791 0.52060533 0.48863016
  0.74526416 0.79603486 0.72558341 0.85717088 0.37165383 0.53863397
  0.72566839 0.1069534  0.66987603 0.51560002 0.35256548 0.67954207
  0.64113781 0.34416205 0.38586427 0.17448361 0.2545574  0.27906572
  0.28722043 0.24363691 0.63379157 0.19256957 0.28793218 0.72532265
  0.58585533 0.73132384 0.66084336 0.57271684 0.63754691 0.03210673
  0.38046243 0.53483066 0.46045632 0.14870072 0.45445679 0.37731511
  0.20918818 0.28719563 0.30454933 0.50172542 0.24158953 0.39555941
  0.50387128 0.18170161 0.39607233 0.61960508 0.39487268 0.33994114
  0.26424145 0.41312965 0.33314938 0.06331188 0.44530876 0.13211153
  0.18922807 0.78947689 0.34730732 0.47238748 0.30682327 0.53814292
  0.26995144 0.7525326  0.22112596 0.3698546  0.27990006 0.73350408
  0.31476798 0.60914114 0.19005758 0.3498392  0.3257219  0.36943096
  0.404211   0.63218407 0.41962097 0.2669218  0.26668209 0.51577148
  0.39434274 0.52878428 0.34774077 0.26605595 0.

In [53]:
#53.How to convert a float (32 bits) array into an integer (32 bits) in place?
#(hint: astype(copy=False))
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
#54. How to read the following file?
#(hint: np.genfromtxt)
#1, 2, 3, 4, 5
#6,  ,  , 7, 8
#,  , 9,10,11
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\1802376389.py:12: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


In [55]:
#55.What is the equivalent of enumerate for numpy arrays? 
#(hint: np.ndenumerate, np.ndindex)
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [56]:
#56.Generate a generic 2D Gaussian-like array 
#(hint: np.meshgrid, np.exp)
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [57]:
#57.How to randomly place p elements in a 2D array? 
#(hint: np.put, np.random.choice)
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
#58. Subtract the mean of each row of a matrix 
#(hint: mean(axis=,keepdims=))
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
Y = X - X.mean(axis=1).reshape(-1, 1)
print(Y)

[[-0.43752645 -0.21382467  0.22614142 -0.24106067  0.11287879  0.01510392
  -0.07111924  0.02481824  0.35857375  0.22601491]
 [-0.10392871 -0.10180854 -0.36698945  0.034749   -0.05710423 -0.29479971
   0.16488995  0.29000741  0.16006863  0.27491564]
 [-0.23670815  0.43454187  0.02133991 -0.36269646  0.25312406  0.15443327
   0.37810911 -0.0090116  -0.24206699 -0.391065  ]
 [ 0.36665214  0.07605686 -0.24387487 -0.18147547  0.39570511 -0.30197379
  -0.41685447  0.01796789  0.03515714  0.25263946]
 [ 0.21298466  0.26694511  0.08008337  0.0931822   0.15121175 -0.32517105
  -0.38336359  0.17056444 -0.44986433  0.18342743]]


In [59]:
#59.How to sort an array by the nth column?
#(hint: argsort)
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[4 1 6]
 [8 6 6]
 [3 0 3]]
[[3 0 3]
 [4 1 6]
 [8 6 6]]


In [60]:
#60.How to tell if a given 2D array has null columns?
#(hint: any, ~)
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())


False


In [61]:
#61.Find the nearest value from a given value in an array (★★☆)
#(hint: np.abs, argmin, flat)
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5505846837140007


In [62]:
#62.Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
#(hint: np.nditer)
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [63]:
#63.Create an array class that has a name attribute 
#(hint: class method)
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


In [64]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
#(hint: np.bincount | np.add.at)
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 3. 4. 1. 5. 2. 1. 2. 5. 3.]
[7. 5. 7. 1. 9. 3. 1. 3. 9. 5.]


In [65]:
#65.How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)
#(hint: np.bincount)
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [66]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
#(hint: np.unique)
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256 )+ I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


In [67]:
#67.Considering a four dimensions array, how to get sum over the last two axis at once? 
#(hint: sum(axis=(-2,-1)))
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[61 64 58 54]
 [64 45 66 51]
 [38 71 70 60]]
[[61 64 58 54]
 [64 45 66 51]
 [38 71 70 60]]


In [68]:
#68.Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
#(hint: np.bincount)
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)



[0.43860264 0.50114686 0.61374607 0.58264964 0.46075972 0.68867824
 0.47954159 0.34176308 0.44622436 0.51658129]


In [69]:
#69. How to get the diagonal of a dot product? 
#(hint: np.diag)
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
np.sum(A * B.T, axis=1)
np.einsum("ij,ji->i", A, B)

array([1.74891577, 1.12606878, 1.25975108, 0.95566325, 1.40743654])

In [70]:
#71.Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
#(hint: array[:, :, None])
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [10]:
#72.How to swap two rows of an array?
#(hint: array[[]] = array[[]])
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [71]:
#73.Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles.
#(hint: repeat, np.roll, np.sort, view, np.unique)
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 0, 19) ( 0, 75) ( 3,  7) ( 3, 16) ( 6, 56) ( 6, 90) ( 7, 16) (10, 16)
 (10, 49) (13, 53) (13, 97) (16, 49) (19, 75) (22, 38) (22, 53) (22, 71)
 (22, 87) (23, 63) (23, 98) (35, 64) (35, 90) (38, 71) (53, 87) (53, 97)
 (56, 90) (63, 98) (64, 74) (64, 76) (64, 90) (74, 76)]


In [8]:
#74.Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)
#(hint: np.repeat)
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [72]:
#75. How to compute averages using a sliding window over an array?
#(hint: np.cumsum)
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [12]:
#76.Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
#(hint: from numpy.lib import stride_tricks)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [73]:
#77.How to negate a boolean, or to change the sign of a float inplace? 
#(hint: np.logical_not, np.negative)
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([ 0.26283896, -0.98386019,  0.68093231, -0.44261374,  0.81677841,
        0.38039795,  0.72188109, -0.36677585, -0.48072012, -0.38695957,
       -0.25840656,  0.97623607, -0.3431975 , -0.42081852, -0.02767887,
       -0.82526052,  0.54949949,  0.20073232,  0.81089309,  0.32687239,
        0.07546293, -0.05638826,  0.00545468, -0.10330522,  0.0387884 ,
       -0.29864288,  0.38220217, -0.4735994 ,  0.16639854,  0.97095521,
        0.07837511,  0.42048057, -0.28592475,  0.4005947 ,  0.51253124,
        0.31209671,  0.52297536,  0.4721955 , -0.2142514 ,  0.14073766,
       -0.29913644, -0.51949891, -0.37843696,  0.25150506,  0.18089498,
        0.41743293,  0.68370545,  0.4248269 , -0.14326415, -0.7670743 ,
        0.49149436,  0.08401725,  0.10833556,  0.73117239,  0.40412731,
       -0.69803637,  0.60449461,  0.60823838, -0.64670974, -0.43878377,
       -0.31811241, -0.35464783, -0.94739552,  0.93518376, -0.62188862,
       -0.15441444,  0.84973013, -0.77646544,  0.44162337, -0.17

In [74]:
#78.Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([(P0,P1,p_i) for p_i in p]))

[[array([[ 6.88690154, -6.76814141],
         [-9.08425656,  2.19083479],
         [-5.00756168,  0.56050154],
         [ 9.16626119, -9.96985101],
         [-9.55457685,  4.06445928],
         [-4.1040686 , -8.17610525],
         [-8.56883569,  1.24704249],
         [ 8.58509958, -2.96252951],
         [-3.56585445, -5.61238716],
         [-4.64956624,  1.37868352]]) array([[ 1.5198879 ,  0.28547518],
                                             [-0.50083914,  6.65331383],
                                             [-8.80923648,  5.92274655],
                                             [ 9.20708421,  9.17842169],
                                             [-5.36370816,  6.99789499],
                                             [-0.46039559, -7.91439374],
                                             [ 6.16250374, -9.87193175],
                                             [ 9.06172903, -0.87034974],
                                             [-5.95065883,  6.6020283 ],
          

C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\4064510352.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  print(np.array([(P0,P1,p_i) for p_i in p]))


In [75]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[3.12692775 3.51801348 1.17034711 0.3350291  7.2130872  7.37828904
 1.8845625  8.10071794 4.26216407 1.18975115]


In [76]:
#80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
#(hint: minimum, maximum)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[4 9 6 3 3 6 6 7 1 3]
 [5 1 9 0 6 1 7 9 7 3]
 [3 3 3 9 9 6 4 6 4 8]
 [0 6 9 3 2 8 6 0 5 4]
 [6 8 9 2 3 6 6 7 2 5]
 [1 6 3 5 2 9 0 9 9 6]
 [2 1 3 3 1 1 8 4 5 3]
 [6 2 6 3 4 4 6 1 0 9]
 [7 6 7 5 5 1 5 8 0 0]
 [8 4 1 6 0 8 7 9 2 8]]
[[0 0 0 0 0]
 [0 4 9 6 3]
 [0 5 1 9 0]
 [0 3 3 3 9]
 [0 0 6 9 3]]


C:\Users\bharath.g\AppData\Local\Temp\ipykernel_8776\3444489543.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


In [87]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [79]:
#82.Compute a matrix rank (★★★)
#(hint: np.linalg.svd) (suggestion: np.linalg.svd)
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)
rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


In [80]:
#83. How to find the most frequent value in an array?
#(hint: np.bincount, argmax)
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

2


In [88]:
#84.Extract all the contiguous 3x3 blocks from a random 10x10 matrix 
#(hint: stride_tricks.as_strided)
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C =np.lib.stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 3 0]
   [1 1 2]
   [3 4 3]]

  [[3 0 2]
   [1 2 4]
   [4 3 0]]

  [[0 2 3]
   [2 4 4]
   [3 0 2]]

  [[2 3 0]
   [4 4 4]
   [0 2 1]]

  [[3 0 2]
   [4 4 3]
   [2 1 4]]

  [[0 2 4]
   [4 3 4]
   [1 4 3]]

  [[2 4 3]
   [3 4 2]
   [4 3 4]]

  [[4 3 2]
   [4 2 3]
   [3 4 0]]]


 [[[1 1 2]
   [3 4 3]
   [1 1 0]]

  [[1 2 4]
   [4 3 0]
   [1 0 0]]

  [[2 4 4]
   [3 0 2]
   [0 0 2]]

  [[4 4 4]
   [0 2 1]
   [0 2 3]]

  [[4 4 3]
   [2 1 4]
   [2 3 0]]

  [[4 3 4]
   [1 4 3]
   [3 0 1]]

  [[3 4 2]
   [4 3 4]
   [0 1 1]]

  [[4 2 3]
   [3 4 0]
   [1 1 0]]]


 [[[3 4 3]
   [1 1 0]
   [3 2 0]]

  [[4 3 0]
   [1 0 0]
   [2 0 3]]

  [[3 0 2]
   [0 0 2]
   [0 3 0]]

  [[0 2 1]
   [0 2 3]
   [3 0 4]]

  [[2 1 4]
   [2 3 0]
   [0 4 3]]

  [[1 4 3]
   [3 0 1]
   [4 3 4]]

  [[4 3 4]
   [0 1 1]
   [3 4 1]]

  [[3 4 0]
   [1 1 0]
   [4 1 2]]]


 [[[1 1 0]
   [3 2 0]
   [4 3 1]]

  [[1 0 0]
   [2 0 3]
   [3 1 0]]

  [[0 0 2]
   [0 3 0]
   [1 0 2]]

  [[0 2 3]
   [3 0 4]
   [0 2 3]]

  [[2 3 0]
   

In [89]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i] 
#(hint: class method)
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  2  3  3 10]
 [ 2  3 15  8  7]
 [ 3 15  9 42 13]
 [ 3  8 42  8 15]
 [10  7 13 15  4]]


In [90]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1))
#(hint: np.tensordot)
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [91]:
#87.Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
#(hint: np.add.reduceat)
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [92]:
#88.How to implement the Game of Life using numpy arrays? 
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 1 0 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 0 1 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  1 1 0 1 0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1
  1 1 1 1 1 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 1 1
  0 0 1 1 1 0 0 0 1 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0 1 1
  1 0 0 0 0 0 0 0 0 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1

In [93]:
#89.How to get the n largest values of an array 
#(hint: np.argsort | np.argpartition)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9997 9996 9998 9999]


In [94]:
#90.Given an arbitrary number of vectors, build the cartesian product (every combinations of every item)
#(hint: np.indices)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [95]:
#91.How to create a record array from a regular array? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [96]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods
#(hint: np.power, *, np.einsum)
x = np.random.randint(5e7)
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.62 µs ± 88.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
221 ns ± 9.39 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


ValueError: einstein sum subscripts string contains too many subscripts for operand 0

In [97]:
#93.Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B?
#(hint: np.where)
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 6 7]


In [98]:
#94.Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[3 3 3]
 [0 3 4]
 [1 1 2]
 [3 1 3]
 [4 4 0]
 [1 2 1]
 [1 2 4]
 [0 2 2]
 [1 0 2]
 [3 3 1]]
[[0 3 4]
 [1 1 2]
 [3 1 3]
 [4 4 0]
 [1 2 1]
 [1 2 4]
 [0 2 2]
 [1 0 2]
 [3 3 1]]
[[0 3 4]
 [1 1 2]
 [3 1 3]
 [4 4 0]
 [1 2 1]
 [1 2 4]
 [0 2 2]
 [1 0 2]
 [3 3 1]]


In [99]:
#95. Convert a vector of ints into a matrix binary representation
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [100]:
#96. Given a two dimensional array, how to extract unique rows? 
#(hint: np.ascontiguousarray)
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 1]
 [1 0 0]
 [1 1 0]
 [1 1 1]]


In [101]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function 
#(hint: np.einsum)
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B) 

array([[0.27464399, 0.25358587, 0.14466999, 0.27862687, 0.19929437,
        0.06009433, 0.27291712, 0.11967153, 0.06807381, 0.20144085],
       [0.77184754, 0.71266672, 0.40657426, 0.78304085, 0.56008824,
        0.16888651, 0.76699444, 0.33631968, 0.19131168, 0.56612063],
       [0.70496237, 0.65090992, 0.37134219, 0.71518572, 0.51155327,
        0.15425149, 0.70052982, 0.30717558, 0.17473339, 0.51706291],
       [0.1799    , 0.1661063 , 0.09476316, 0.1825089 , 0.13054375,
        0.03936358, 0.17876885, 0.07838842, 0.04459037, 0.13194976],
       [0.29935439, 0.27640162, 0.15768631, 0.30369562, 0.21722538,
        0.06550117, 0.29747216, 0.13043868, 0.07419858, 0.21956499],
       [0.28833385, 0.26622607, 0.15188119, 0.29251526, 0.20922836,
        0.06308979, 0.28652091, 0.12563666, 0.07146701, 0.21148184],
       [0.10614554, 0.09800691, 0.05591265, 0.10768486, 0.07702411,
        0.02322551, 0.10547814, 0.04625115, 0.02630945, 0.07785369],
       [0.58745721, 0.54241438, 0.3094458

In [102]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples?
#(hint: np.cumsum, np.interp)
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [103]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
#(hint: np.logical_and.reduce, np.mod)
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [104]:
#100.Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means).
#(hint: np.percentile)
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.24600268  0.15573152]
